### ISSUE TITLE
Converter should allow in-place conversion

### ISSUE THREAD

**Issue by patrickuhlmann** [asyncapi/converter-js#93]
#### Reason/Context

I think often you want to run the upgrade on a file and see what has changed in git. In such a case you want the converter to directly modify that file instead of creating a new file.

I executed the command like this:
`asyncapi-converter asyncapi.yaml > asyncapi.yaml`

but this resulted in an empty file. 

As a workaround I run it like this:
```
asyncapi-converter asyncapi.yaml > asyncapi_updated.yaml
mv asyncapi_updated.yaml asyncapi.yaml
```
this worked but it would be nice to do it in one step.

#### Description

To support in-place update, you could add a command line switch -i, e. g.
`asyncapi-converter -i asyncapi.yaml`

**Comment by jonaslagoni** [comment]
Completely agree, I ran into the same problem 👍

**Comment by magicmatatjahu** [comment]
@patrickuhlmann We are in the process of moving CLI converter to our main CLI, here is the PR https://github.com/asyncapi/cli/pull/188. Of course I understand the problem and it is indeed problematic but perhaps instead of `-i` we should use the `-o` flag? Of course the output should be given as the name of the same file but I guess that would be more verbose as just `-i`. What do you think?

NOTE: If we will move CLI to the `cli` repo, don't worry, cli will be there unless we will release `1.0.0` version of converter, followed by semver :)

**Comment by patrickuhlmann** [comment]
@magicmatatjahu I think -o would be fine too (to be consistent with the other commands). I just suggested -i for simplicity.

**Comment by magicmatatjahu** [comment]
@patrickuhlmann Hi! Please update converter to the `0.9.0` version and you can use `-o` flag https://github.com/asyncapi/converter-js#from-cli

![image](https://user-images.githubusercontent.com/20404945/154674381-caca9c76-e16c-47b4-a80c-c793cba8703d.png)

**Comment by patrickuhlmann** [comment]
Thanks. Nice work!

**Comment by jonaslagoni** [comment]
Awesome @magicmatatjahu 🎉
